var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/affiliate/links/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ddd4472._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_1761b663._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_admin_layout_tsx_b509232f._.js")
R.c("server/chunks/ssr/frontend_src_app_admin_affiliate_layout_tsx_95ef5099._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_admin_affiliate_links_page_actions_7ed1291d.js")
R.m(953570)
module.exports=R.m(953570).exports
