#!/bin/bash

clear
echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║         🔧 FIX GOOGLE DRIVE PERMISSION - HƯỚNG DẪN NHANH          ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "❌ LỖI HIỆN TẠI:"
echo "   File not found: 1kSEvP8QlhhZoOjtemtLuKA_LkuWr2OTG"
echo ""
echo "✅ CÁCH SỬA (3 BƯỚC):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📧 BƯỚC 1: Copy email Service Account này:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   app-taza-group-drive-tazagroup@tazagroup-480011.iam.gserviceaccount.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🌐 BƯỚC 2: Mở link folder Google Drive này:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   https://drive.google.com/drive/folders/1kSEvP8QlhhZoOjtemtLuKA_LkuWr2OTG"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔐 BƯỚC 3: Share folder với Service Account:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   1. Click nút 'Share' / 'Chia sẻ' (góc trên bên phải)"
echo "   2. Paste email Service Account vào ô 'Add people'"
echo "   3. Chọn quyền: 'Editor' / 'Người chỉnh sửa'"
echo "   4. BỎ TÍCH 'Notify people' (không cần thông báo)"
echo "   5. Click 'Share' / 'Chia sẻ'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ SAU KHI SHARE XONG:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   🕒 Đợi 1-2 phút để Google đồng bộ permissions"
echo ""
echo "   🧪 Chạy test để kiểm tra:"
echo "      cd /chikiet/kataoffical/shoprausach/backend"
echo "      node test-google-drive-direct.js"
echo ""
echo "   🔄 Hoặc chạy script test tổng hợp:"
echo "      ./test-google-drive-permission.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 Hướng dẫn chi tiết:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   cat FIX-GOOGLE-DRIVE-PERMISSION.md"
echo ""
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
