import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedWebsiteSettings() {
  console.log('🌱 Seeding Website Settings...');

  const settings: Prisma.WebsiteSettingCreateInput[] = [
    // ===== GENERAL SETTINGS =====
    {
      key: 'site.name',
      value: 'Rau Sạch Trần Gia',
      type: 'TEXT',
      category: 'GENERAL',
      label: 'Tên Website',
      description: 'Tên chính thức của website',
      group: 'basic',
      order: 1,
      isPublic: true,
    },
    {
      key: 'site.tagline',
      value: 'Nông Sản Thực Phẩm Sạch',
      type: 'TEXT',
      category: 'GENERAL',
      label: 'Slogan',
      description: 'Câu slogan của website',
      group: 'basic',
      order: 2,
      isPublic: true,
    },
    {
      key: 'site.description',
      value: 'Chuyên cung cấp rau sạch, thực phẩm organic chất lượng cao',
      type: 'TEXTAREA',
      category: 'GENERAL',
      label: 'Mô tả Website',
      description: 'Mô tả ngắn về website',
      group: 'basic',
      order: 3,
      isPublic: true,
    },

    // ===== HEADER SETTINGS =====
    {
      key: 'header.logo',
      value: '/assets/images/logo.svg',
      type: 'IMAGE',
      category: 'HEADER',
      label: 'Logo Header',
      description: 'Logo hiển thị ở header',
      group: 'branding',
      order: 1,
      isPublic: true,
    },
    {
      key: 'header.logo_width',
      value: '80',
      type: 'NUMBER',
      category: 'HEADER',
      label: 'Chiều rộng Logo (px)',
      description: 'Kích thước chiều rộng của logo',
      group: 'branding',
      order: 2,
      isPublic: true,
      validation: JSON.stringify({ min: 40, max: 200 }),
    },
    {
      key: 'header.background_color',
      value: '#57A345',
      type: 'COLOR',
      category: 'HEADER',
      label: 'Màu nền Header',
      description: 'Màu nền của header',
      group: 'styling',
      order: 3,
      isPublic: true,
    },
    {
      key: 'header.text_color',
      value: '#FFFFFF',
      type: 'COLOR',
      category: 'HEADER',
      label: 'Màu chữ Header',
      description: 'Màu chữ của header',
      group: 'styling',
      order: 4,
      isPublic: true,
    },
    {
      key: 'header.show_search',
      value: 'true',
      type: 'BOOLEAN',
      category: 'HEADER',
      label: 'Hiển thị tìm kiếm',
      description: 'Bật/tắt thanh tìm kiếm ở header',
      group: 'features',
      order: 5,
      isPublic: true,
    },
    {
      key: 'header.show_cart',
      value: 'true',
      type: 'BOOLEAN',
      category: 'HEADER',
      label: 'Hiển thị giỏ hàng',
      description: 'Bật/tắt icon giỏ hàng',
      group: 'features',
      order: 6,
      isPublic: true,
    },
    {
      key: 'header.show_user_menu',
      value: 'true',
      type: 'BOOLEAN',
      category: 'HEADER',
      label: 'Hiển thị menu người dùng',
      description: 'Bật/tắt menu đăng nhập/tài khoản',
      group: 'features',
      order: 7,
      isPublic: true,
    },
    {
      key: 'header.banner_enabled',
      value: 'true',
      type: 'BOOLEAN',
      category: 'HEADER',
      label: 'Hiển thị Banner',
      description: 'Bật/tắt carousel banner ở header',
      group: 'banner',
      order: 8,
      isPublic: true,
    },
    {
      key: 'header.banner_height',
      value: '208',
      type: 'NUMBER',
      category: 'HEADER',
      label: 'Chiều cao Banner (px)',
      description: 'Chiều cao của banner carousel',
      group: 'banner',
      order: 9,
      isPublic: true,
      validation: JSON.stringify({ min: 100, max: 500 }),
    },
    {
      key: 'header.banner_autoplay',
      value: 'true',
      type: 'BOOLEAN',
      category: 'HEADER',
      label: 'Banner tự động chuyển',
      description: 'Banner tự động chuyển slide',
      group: 'banner',
      order: 10,
      isPublic: true,
    },
    {
      key: 'header.banner_interval',
      value: '5000',
      type: 'NUMBER',
      category: 'HEADER',
      label: 'Thời gian chuyển Banner (ms)',
      description: 'Thời gian giữa các slide (milliseconds)',
      group: 'banner',
      order: 11,
      isPublic: true,
      validation: JSON.stringify({ min: 2000, max: 10000 }),
    },

    // ===== FOOTER SETTINGS =====
    {
      key: 'footer.background_color',
      value: '#000000',
      type: 'COLOR',
      category: 'FOOTER',
      label: 'Màu nền Footer',
      description: 'Màu nền của footer',
      group: 'styling',
      order: 1,
      isPublic: true,
    },
    {
      key: 'footer.text_color',
      value: '#FFFFFF',
      type: 'COLOR',
      category: 'FOOTER',
      label: 'Màu chữ Footer',
      description: 'Màu chữ của footer',
      group: 'styling',
      order: 2,
      isPublic: true,
    },
    {
      key: 'footer.show_visitor_stats',
      value: 'true',
      type: 'BOOLEAN',
      category: 'FOOTER',
      label: 'Hiển thị thống kê truy cập',
      description: 'Bật/tắt thống kê số người truy cập',
      group: 'features',
      order: 3,
      isPublic: true,
    },
    {
      key: 'footer.show_social_links',
      value: 'true',
      type: 'BOOLEAN',
      category: 'FOOTER',
      label: 'Hiển thị mạng xã hội',
      description: 'Bật/tắt các icon mạng xã hội',
      group: 'features',
      order: 4,
      isPublic: true,
    },

    // ===== CONTACT SETTINGS =====
    {
      key: 'contact.company_name',
      value: 'CTY TNHH NÔNG SẢN THỰC PHẨM TRẦN GIA',
      type: 'TEXT',
      category: 'CONTACT',
      label: 'Tên công ty',
      description: 'Tên đầy đủ của công ty',
      group: 'company',
      order: 1,
      isPublic: true,
    },
    {
      key: 'contact.address',
      value: 'Tầng 3, An Phú Plaza, 117-119 Lý Chính Thắng P. Võ Thị Sáu, Q.3, TPHCM',
      type: 'TEXTAREA',
      category: 'CONTACT',
      label: 'Địa chỉ',
      description: 'Địa chỉ công ty',
      group: 'company',
      order: 2,
      isPublic: true,
    },
    {
      key: 'contact.phone',
      value: '0865770009',
      type: 'TEXT',
      category: 'CONTACT',
      label: 'Số điện thoại',
      description: 'Hotline chính',
      group: 'company',
      order: 3,
      isPublic: true,
    },
    {
      key: 'contact.phone_display',
      value: '0865.77.0009',
      type: 'TEXT',
      category: 'CONTACT',
      label: 'Số điện thoại hiển thị',
      description: 'Số điện thoại định dạng để hiển thị',
      group: 'company',
      order: 4,
      isPublic: true,
    },
    {
      key: 'contact.email',
      value: 'mart.rausachtrangia@gmail.com',
      type: 'TEXT',
      category: 'CONTACT',
      label: 'Email',
      description: 'Email liên hệ chính',
      group: 'company',
      order: 5,
      isPublic: true,
    },

    // ===== SOCIAL SETTINGS =====
    {
      key: 'social.facebook',
      value: 'https://www.facebook.com/rausachtrangia2011',
      type: 'URL',
      category: 'SOCIAL',
      label: 'Facebook URL',
      description: 'Link trang Facebook',
      group: 'links',
      order: 1,
      isPublic: true,
    },
    {
      key: 'social.facebook_enabled',
      value: 'true',
      type: 'BOOLEAN',
      category: 'SOCIAL',
      label: 'Hiển thị Facebook',
      description: 'Bật/tắt link Facebook',
      group: 'links',
      order: 2,
      isPublic: true,
    },
    {
      key: 'social.tiktok',
      value: 'https://www.tiktok.com/@rausachtrangia.com?_t=8maDzCUcrPs&_r=1',
      type: 'URL',
      category: 'SOCIAL',
      label: 'TikTok URL',
      description: 'Link trang TikTok',
      group: 'links',
      order: 3,
      isPublic: true,
    },
    {
      key: 'social.tiktok_enabled',
      value: 'true',
      type: 'BOOLEAN',
      category: 'SOCIAL',
      label: 'Hiển thị TikTok',
      description: 'Bật/tắt link TikTok',
      group: 'links',
      order: 4,
      isPublic: true,
    },
    {
      key: 'social.youtube',
      value: 'https://www.youtube.com/@rausachtrangia1649',
      type: 'URL',
      category: 'SOCIAL',
      label: 'YouTube URL',
      description: 'Link kênh YouTube',
      group: 'links',
      order: 5,
      isPublic: true,
    },
    {
      key: 'social.youtube_enabled',
      value: 'true',
      type: 'BOOLEAN',
      category: 'SOCIAL',
      label: 'Hiển thị YouTube',
      description: 'Bật/tắt link YouTube',
      group: 'links',
      order: 6,
      isPublic: true,
    },

    // ===== SEO SETTINGS =====
    {
      key: 'seo.meta_title',
      value: 'Rau Sạch Trần Gia - Nông Sản Thực Phẩm Sạch',
      type: 'TEXT',
      category: 'SEO',
      label: 'Meta Title',
      description: 'Tiêu đề SEO mặc định',
      group: 'meta',
      order: 1,
      isPublic: true,
    },
    {
      key: 'seo.meta_description',
      value: 'Chuyên cung cấp rau sạch, thực phẩm organic chất lượng cao tại TPHCM',
      type: 'TEXTAREA',
      category: 'SEO',
      label: 'Meta Description',
      description: 'Mô tả SEO mặc định',
      group: 'meta',
      order: 2,
      isPublic: true,
    },
    {
      key: 'seo.keywords',
      value: 'rau sạch, thực phẩm organic, nông sản, rau củ quả, TPHCM',
      type: 'TEXTAREA',
      category: 'SEO',
      label: 'Keywords',
      description: 'Từ khóa SEO (phân cách bằng dấu phẩy)',
      group: 'meta',
      order: 3,
      isPublic: true,
    },
    {
      key: 'seo.og_image',
      value: '/assets/images/logo.svg',
      type: 'IMAGE',
      category: 'SEO',
      label: 'OG Image',
      description: 'Ảnh hiển thị khi share lên mạng xã hội',
      group: 'social_meta',
      order: 4,
      isPublic: true,
    },

    // ===== APPEARANCE SETTINGS =====
    {
      key: 'appearance.primary_color',
      value: '#57A345',
      type: 'COLOR',
      category: 'APPEARANCE',
      label: 'Màu chính',
      description: 'Màu chủ đạo của website',
      group: 'colors',
      order: 1,
      isPublic: true,
    },
    {
      key: 'appearance.secondary_color',
      value: '#FAA61A',
      type: 'COLOR',
      category: 'APPEARANCE',
      label: 'Màu phụ',
      description: 'Màu phụ của website',
      group: 'colors',
      order: 2,
      isPublic: true,
    },
    {
      key: 'appearance.accent_color',
      value: '#65b009',
      type: 'COLOR',
      category: 'APPEARANCE',
      label: 'Màu nhấn',
      description: 'Màu nhấn (highlights)',
      group: 'colors',
      order: 3,
      isPublic: true,
    },
  ];

  for (const setting of settings) {
    await prisma.websiteSetting.upsert({
      where: { key: setting.key },
      update: setting,
      create: setting,
    });
  }

  console.log(`✅ Created/Updated ${settings.length} website settings`);
}

// Run if called directly
if (require.main === module) {
  seedWebsiteSettings()
    .then(() => {
      console.log('✅ Website Settings seeding completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('❌ Error seeding website settings:', error);
      process.exit(1);
    });
}
