#!/bin/bash

# Test Join Campaign UI Components
# Tests: JoinCampaignModal, CampaignBrowser, ApplicationReviewPanel

echo "🧪 Testing Join Campaign UI Components..."
echo ""

echo "📋 Test Checklist:"
echo ""

echo "1️⃣ CampaignBrowser Component"
echo "   ✓ Navigate to /admin/affiliate/browse"
echo "   ✓ See campaign grid (1/2/3 columns responsive)"
echo "   ✓ Search functionality works"
echo "   ✓ Commission filter works (All/Percentage/Fixed)"
echo "   ✓ Status filter works (All/Active/Paused/Draft)"
echo "   ✓ Application status badges show correctly"
echo "   ✓ Join button states work (Join/Pending/Approved/Rejected)"
echo ""

echo "2️⃣ JoinCampaignModal Component"
echo "   ✓ Click 'Join Campaign' button"
echo "   ✓ Modal opens with campaign details"
echo "   ✓ Commission info displays correctly"
echo "   ✓ Cookie duration shows"
echo "   ✓ Campaign type and status visible"
echo "   ✓ Message input works"
echo "   ✓ Required message for private campaigns"
echo "   ✓ Submit button works"
echo "   ✓ Loading state during submission"
echo "   ✓ Error handling displays"
echo "   ✓ Success closes modal"
echo "   ✓ Status badge updates after join"
echo ""

echo "3️⃣ ApplicationReviewPanel Component"
echo "   ✓ Navigate to /admin/affiliate/campaigns/:id/applications"
echo "   ✓ Stats cards show (Pending/Approved/Rejected)"
echo "   ✓ Applications segmented correctly"
echo "   ✓ Affiliate info displays (name, email, website)"
echo "   ✓ Application message visible"
echo "   ✓ Approve button works"
echo "   ✓ Reject button works"
echo "   ✓ Review dialog opens"
echo "   ✓ Reason input works"
echo "   ✓ Submit review works"
echo "   ✓ Application moves to correct section"
echo "   ✓ Counts update"
echo "   ✓ Rejection reason displays"
echo ""

echo "4️⃣ CampaignManagement Integration"
echo "   ✓ 'Browse All Campaigns' button visible (affiliates)"
echo "   ✓ 'View Applications' button on campaigns (merchants)"
echo "   ✓ Buttons link to correct pages"
echo ""

echo "5️⃣ Responsive Design"
echo "   ✓ Mobile (320px-768px): 1 column"
echo "   ✓ Tablet (768px-1024px): 2 columns"
echo "   ✓ Desktop (1024px+): 3 columns"
echo "   ✓ Modal adapts to screen size"
echo "   ✓ Filters stack on mobile"
echo ""

echo "6️⃣ Dark Mode"
echo "   ✓ All components work in dark mode"
echo "   ✓ Colors properly inverted"
echo "   ✓ Contrast maintained"
echo ""

echo "7️⃣ Error Handling"
echo "   ✓ Network errors show message"
echo "   ✓ Validation errors handled"
echo "   ✓ Already joined error"
echo "   ✓ Campaign full error"
echo "   ✓ Unauthorized errors"
echo ""

echo "8️⃣ Loading States"
echo "   ✓ Skeleton loaders on initial load"
echo "   ✓ Spinner on buttons during mutation"
echo "   ✓ Disabled states during processing"
echo ""

echo ""
echo "✅ Manual Testing Steps:"
echo ""
echo "AFFILIATE FLOW:"
echo "1. Login as affiliate"
echo "2. Go to /admin/affiliate/campaigns"
echo "3. Click 'Browse All Campaigns'"
echo "4. Search for a campaign"
echo "5. Click 'Join Campaign' on any active campaign"
echo "6. Fill in message (if required)"
echo "7. Submit"
echo "8. Verify status badge appears"
echo "9. Check button changes to 'Pending' or 'Already Joined'"
echo ""

echo "MERCHANT FLOW:"
echo "10. Login as merchant"
echo "11. Go to /admin/affiliate/campaigns"
echo "12. Click Users icon on any campaign"
echo "13. Navigate to applications page"
echo "14. See pending applications"
echo "15. Click 'Approve' on an application"
echo "16. Enter optional message"
echo "17. Submit"
echo "18. Verify application moves to 'Approved' section"
echo "19. Verify counts update"
echo ""

echo "REJECTION FLOW:"
echo "20. Click 'Reject' on pending application"
echo "21. Enter rejection reason"
echo "22. Submit"
echo "23. Verify application in 'Rejected' section"
echo "24. Verify reason displays on card"
echo ""

echo "📊 Component Checklist:"
echo ""
echo "Files to verify exist:"
echo "✓ /frontend/src/components/affiliate/campaigns/JoinCampaignModal.tsx"
echo "✓ /frontend/src/components/affiliate/campaigns/CampaignBrowser.tsx"
echo "✓ /frontend/src/components/affiliate/campaigns/ApplicationReviewPanel.tsx"
echo "✓ /frontend/src/app/admin/affiliate/browse/page.tsx"
echo "✓ /frontend/src/app/admin/affiliate/campaigns/[id]/applications/page.tsx"
echo ""

echo "GraphQL operations to verify:"
echo "✓ JOIN_CAMPAIGN mutation"
echo "✓ REVIEW_CAMPAIGN_APPLICATION mutation"
echo "✓ DELETE_AFFILIATE_CAMPAIGN mutation"
echo "✓ GET_MY_CAMPAIGN_APPLICATIONS query"
echo "✓ GET_CAMPAIGN_APPLICATIONS query"
echo ""

echo "🎉 Testing Guide Complete!"
echo ""
echo "Run frontend with: cd frontend && bun dev"
echo "Open browser at: http://localhost:3000"
echo "Test both affiliate and merchant flows"
echo ""
