var R=require("../../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/lms/admin/courses/[id]/edit/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9ee1663c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_ead03555._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_lms_layout_tsx_ae765dfa._.js")
R.c("server/chunks/ssr/frontend_src_app_lms_admin_layout_tsx_39c9abcc._.js")
R.c("server/chunks/ssr/ceffb__next-internal_server_app_lms_admin_courses_[id]_edit_page_actions_8c2467a8.js")
R.m(203697)
module.exports=R.m(203697).exports
