var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/lms/instructor/courses/create/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__091d5258._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_b45c3731._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_lms_layout_tsx_ae765dfa._.js")
R.c("server/chunks/ssr/frontend_src_app_lms_instructor_layout_tsx_679cf741._.js")
R.c("server/chunks/ssr/ceffb__next-internal_server_app_lms_instructor_courses_create_page_actions_36767404.js")
R.m(935517)
module.exports=R.m(935517).exports
