var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/products/create/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2da58f4e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_27d22eb5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_admin_layout_tsx_b509232f._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_admin_products_create_page_actions_f47d366a.js")
R.m(198269)
module.exports=R.m(198269).exports
