var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/lms/admin/students/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__16244272._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_f39cd7d8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_lms_layout_tsx_ae765dfa._.js")
R.c("server/chunks/ssr/frontend_src_app_lms_admin_layout_tsx_39c9abcc._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_lms_admin_students_[id]_page_actions_a58342a5.js")
R.m(776326)
module.exports=R.m(776326).exports
