var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(projects)/projects/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4d678c1b._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_7a5d2bfe._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_(projects)_layout_tsx_2d8d946e._.js")
R.c("server/chunks/ssr/ceffb__next-internal_server_app_(projects)_projects_settings_page_actions_8ca4a7fa.js")
R.m(138836)
module.exports=R.m(138836).exports
