var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c0310cdb._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_842512f8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__31769dbf._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app__global-error_page_actions_33753f04.js")
R.m(985646)
module.exports=R.m(985646).exports
