var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/hr/onboarding/new/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f05cd416._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_5a23fcf3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_admin_layout_tsx_b509232f._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_admin_hr_onboarding_new_page_actions_8f95bd12.js")
R.m(361155)
module.exports=R.m(361155).exports
