var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/demo/carousel/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d4b1636._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_809a7fa9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_demo_layout_tsx_a1f1d31b._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_demo_carousel_page_actions_5c54d403.js")
R.m(868559)
module.exports=R.m(868559).exports
