#!/bin/bash

echo ""
echo "🔍 KIỂM TRA QUYỀN TRUY CẬP GOOGLE DRIVE"
echo "========================================"
echo ""
echo "📧 Service Account Email:"
echo "   app-taza-group-drive-tazagroup@tazagroup-480011.iam.gserviceaccount.com"
echo ""
echo "📁 Folder URL:"
echo "   https://drive.google.com/drive/folders/1kSEvP8QlhhZoOjtemtLuKA_LkuWr2OTG"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔴 VUI LÒNG KIỂM TRA LẠI TRONG GOOGLE DRIVE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Mở folder: https://drive.google.com/drive/folders/1kSEvP8QlhhZoOjtemtLuKA_LkuWr2OTG"
echo ""
echo "2. Click phải vào folder → 'Share' / 'Chia sẻ'"
echo ""
echo "3. Trong danh sách 'Những người có quyền truy cập'"
echo "   CÓ THẤY email này không?"
echo ""
echo "   app-taza-group-drive-tazagroup@tazagroup-480011.iam.gserviceaccount.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 NẾU KHÔNG THẤY EMAIL TRONG DANH SÁCH:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "➡️  Có thể bạn đã:"
echo "    - Chỉ mới NHẬP email nhưng chưa click 'Gửi' / 'Send'"
echo "    - Click 'Xong' trước khi click 'Gửi'"
echo "    - Share rồi nhưng Google chưa lưu (do lỗi mạng)"
echo ""
echo "✅ HÃY LÀM LẠI:"
echo ""
echo "    1. Click 'Share' / 'Chia sẻ'"
echo "    2. Paste email:"
echo "       app-taza-group-drive-tazagroup@tazagroup-480011.iam.gserviceaccount.com"
echo "    3. Chọn quyền: 'Người chỉnh sửa' / 'Editor'"
echo "    4. 🔴 QUAN TRỌNG: Click nút 'Gửi' / 'Send' màu xanh"
echo "    5. Đợi thấy email xuất hiện trong danh sách"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 NẾU ĐÃ THẤY EMAIL TRONG DANH SÁCH:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "➡️  Kiểm tra quyền:"
echo "    - Phải là 'Người chỉnh sửa' / 'Editor'"
echo "    - KHÔNG PHẢI 'Người xem' / 'Viewer'"
echo ""
echo "➡️  Nếu quyền đúng rồi, thử:"
echo "    1. XÓA Service Account khỏi folder"
echo "    2. Đợi 10 giây"
echo "    3. THÊM LẠI với quyền Editor"
echo "    4. Đợi 1-2 phút"
echo "    5. Chạy test lại"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Sau khi đã XÁC NHẬN email trong danh sách, nhấn Enter để test..."
read

echo ""
echo "🧪 Testing folder access..."
echo ""

node test-google-drive-direct.js
