// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/phone/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phone">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/phone/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(projects)/projects/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(projects)/projects/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(projects)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../src/app/(projects)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(projects)/projects/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(projects)/projects/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(projects)/projects/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/team">> = Specific
  const handler = {} as typeof import("../../src/app/(projects)/projects/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(projects)/projects/views/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/views">> = Specific
  const handler = {} as typeof import("../../src/app/(projects)/projects/views/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/test-dynamic-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-dynamic-demo">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/test-dynamic-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/bai-viet/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bai-viet/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/bai-viet/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/bai-viet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bai-viet">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/bai-viet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/gio-hang/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gio-hang">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/gio-hang/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/san-pham/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/san-pham/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/san-pham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/san-pham">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/san-pham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/thanh-toan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thanh-toan">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/thanh-toan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/browse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate/browse">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/browse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/campaigns/[id]/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate/campaigns/[id]/applications">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/campaigns/[id]/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate/campaigns">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/links/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate/links">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/links/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/affiliate/payments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/callcenter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/callcenter">> = Specific
  const handler = {} as typeof import("../../src/app/admin/callcenter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/data-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data-management">> = Specific
  const handler = {} as typeof import("../../src/app/admin/data-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dynamic-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dynamic-demo">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dynamic-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/filemanager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/filemanager">> = Specific
  const handler = {} as typeof import("../../src/app/admin/filemanager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/employee/[id]/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/employee/[id]/documents">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/employee/[id]/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/employee/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/employee/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/employee/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/employee/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/employee/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/employee/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/employee/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/employee/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/employee/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/employees">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/offboarding/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/offboarding/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/offboarding/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/offboarding/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/offboarding/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/offboarding/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/offboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/offboarding">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/offboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/onboarding/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/onboarding/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/onboarding/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/onboarding/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/onboarding/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/onboarding/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/onboarding">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/hr/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/hr/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/hr/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/menu">> = Specific
  const handler = {} as typeof import("../../src/app/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pagebuilder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pagebuilder">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pagebuilder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products/create">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/products">> = Specific
  const handler = {} as typeof import("../../src/app/admin/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/projects">> = Specific
  const handler = {} as typeof import("../../src/app/admin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/request-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/request-access">> = Specific
  const handler = {} as typeof import("../../src/app/admin/request-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/website/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/website">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/website/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support-chat/ai-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support-chat/ai-settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support-chat/ai-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/support-chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/support-chat">> = Specific
  const handler = {} as typeof import("../../src/app/admin/support-chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tasks/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tasks/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/affiliate-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/affiliate-access">> = Specific
  const handler = {} as typeof import("../../src/app/affiliate-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/advanced-table-demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/advanced-table-demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/advanced-table-demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/ai">> = Specific
  const handler = {} as typeof import("../../src/app/demo/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/carousel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/carousel">> = Specific
  const handler = {} as typeof import("../../src/app/demo/carousel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/chatbot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/chatbot">> = Specific
  const handler = {} as typeof import("../../src/app/demo/chatbot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/login">> = Specific
  const handler = {} as typeof import("../../src/app/demo/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/demo/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/pwa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/pwa">> = Specific
  const handler = {} as typeof import("../../src/app/demo/pwa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/toast/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo/toast">> = Specific
  const handler = {} as typeof import("../../src/app/demo/toast/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ketoan/detailhoadon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ketoan/detailhoadon">> = Specific
  const handler = {} as typeof import("../../src/app/ketoan/detailhoadon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ketoan/listhoadon/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ketoan/listhoadon">> = Specific
  const handler = {} as typeof import("../../src/app/ketoan/listhoadon/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ketoan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ketoan">> = Specific
  const handler = {} as typeof import("../../src/app/ketoan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ketoan/sanpham/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ketoan/sanpham">> = Specific
  const handler = {} as typeof import("../../src/app/ketoan/sanpham/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ketoan/xuatnhapton/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ketoan/xuatnhapton">> = Specific
  const handler = {} as typeof import("../../src/app/ketoan/xuatnhapton/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/categories">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/courses/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/courses/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/courses/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/courses/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/courses/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/courses/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/courses/create-with-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/courses/create-with-ai">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/courses/create-with-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/courses/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/courses/create">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/courses/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/courses">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/enrollments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/enrollments">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/enrollments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/instructors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/instructors">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/instructors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/quizzes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/quizzes">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/quizzes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/students/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/students/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/students/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/admin/students">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/certificates/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/certificates/verify">> = Specific
  const handler = {} as typeof import("../../src/app/lms/certificates/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/courses/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/courses/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/lms/courses/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/courses">> = Specific
  const handler = {} as typeof import("../../src/app/lms/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/courses/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/instructor/courses/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/courses/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/courses/[id]/lessons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/instructor/courses/[id]/lessons">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/courses/[id]/lessons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/courses/[id]/manage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/instructor/courses/[id]/manage">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/courses/[id]/manage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/courses/[id]/quizzes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/instructor/courses/[id]/quizzes">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/courses/[id]/quizzes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/courses/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/instructor/courses/create">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/courses/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/instructor/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/learn/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/learn/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/lms/learn/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/my-certificates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/my-certificates">> = Specific
  const handler = {} as typeof import("../../src/app/lms/my-certificates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/my-learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/my-learning">> = Specific
  const handler = {} as typeof import("../../src/app/lms/my-learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms">> = Specific
  const handler = {} as typeof import("../../src/app/lms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lms/student">> = Specific
  const handler = {} as typeof import("../../src/app/lms/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ketoan/normalize-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ketoan/normalize-products">> = Specific
  const handler = {} as typeof import("../../src/app/api/ketoan/normalize-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(projects)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(projects)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(website)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(website)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/affiliate/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/affiliate">> = Specific
  const handler = {} as typeof import("../../src/app/admin/affiliate/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../src/app/demo/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/demo/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/demo/login">> = Specific
  const handler = {} as typeof import("../../src/app/demo/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ketoan/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/ketoan">> = Specific
  const handler = {} as typeof import("../../src/app/ketoan/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lms/admin">> = Specific
  const handler = {} as typeof import("../../src/app/lms/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/instructor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lms/instructor">> = Specific
  const handler = {} as typeof import("../../src/app/lms/instructor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lms/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/lms">> = Specific
  const handler = {} as typeof import("../../src/app/lms/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
