var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/ketoan/detailhoadon/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__71e32625._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_ed05ab44._.js")
R.c("server/chunks/ssr/_381f9f8d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7987500c._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_13f97e60._.js")
R.c("server/chunks/ssr/node_modules__bun_eec8fead._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_global-error_f1be2e82.js")
R.c("server/chunks/ssr/[root-of-the-server]__bf73d1a0._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_7b08e37e._.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_forbidden_b4abc5b2.js")
R.c("server/chunks/ssr/e1dcf_next_dist_client_components_builtin_unauthorized_17e3d95e.js")
R.c("server/chunks/ssr/frontend_src_app_ketoan_layout_tsx_0fadda28._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_ketoan_detailhoadon_page_actions_98d73b88.js")
R.m(544028)
module.exports=R.m(544028).exports
